### PR TITLE
add manual dataset class for importing data into dataset manually without using csv files

### PR DESCRIPTION
**Pull request by lazargugleta**
This extended class will help with easier data import for usages without csv files.
The class itself operates with a simple randomized cross validation of data and separation into train and test data based of the trainPercentage that is passed into the constructor.

### CODE REVIEW

**Comment by ferortega** [comment]
Thank you for your contribution. Could you add an optional random seed to the constructor in order to ensure the reproducibility of the train/test split?

**Comment by lazargugleta** [comment]
> Thank you for your contribution. Could you add an optional random seed to the constructor in order to ensure the reproducibility of the train/test split?

Yeah sure! It is now either a random seed or a Long seed to be set.

**Review by ferortega — APPROVED** [review]

**Comment by ferortega** [comment]
Merged! Thank you!

**Comment by lazargugleta** [comment]
> Merged! Thank you!

Thank you as well! Nice library!

**Pull request merged**
